# Generated by Django 2.2.19 on 2021-07-28 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0003_auto_20210728_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Введите целое число больше 0 для времени готовки.')], verbose_name='время готовки, мин'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Введите целое число больше 0 для количества.')], verbose_name='количество'),
        ),
    ]
